./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 401 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 405 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 409 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 413 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 417 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 421 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 425 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 429 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 433 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 437 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 441 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 445 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 449 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 453 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 457 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 461 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 465 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 469 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 473 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 477 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 481 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 485 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 489 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 493 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 497 0 -psm example/psm.txt -wl example/custom_workload_1.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 401 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 405 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 409 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 413 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 417 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 421 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 425 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 429 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 433 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 437 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 441 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 445 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 449 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 453 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 457 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 461 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 465 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 469 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 473 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 477 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 481 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 485 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 489 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 493 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 497 0 -psm example/psm.txt -wl example/custom_workload_2.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/Generated_workload_1.1.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/Generated_workload_1.2.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 401 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 405 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 409 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 413 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 417 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 421 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 425 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 429 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 433 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 437 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 441 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 445 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 449 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 453 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 457 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 461 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 465 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 469 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 473 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 477 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 481 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 485 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 489 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 493 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 497 0 -psm example/psm.txt -wl example/Generated_workload_1.3.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 401 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 405 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 409 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 413 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 417 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 421 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 425 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 429 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 433 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 437 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 441 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 445 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 449 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 453 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 457 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 461 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 465 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 469 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 473 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 477 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 481 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 485 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 489 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 493 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 497 0 -psm example/psm.txt -wl example/Generated_workload_1.4.txt &
./dpm_simulator -t 1 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 5 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 9 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 13 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 17 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 21 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 25 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 29 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 33 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 37 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 41 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 45 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 49 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 53 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 57 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 61 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 65 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 69 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 73 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 77 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 81 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 85 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 89 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 93 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 97 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 101 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 105 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 109 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 113 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 117 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 121 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 125 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 129 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 133 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 137 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 141 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 145 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 149 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 153 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 157 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 161 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 165 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 169 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 173 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 177 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 181 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 185 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 189 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 193 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 197 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 201 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 205 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 209 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 213 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 217 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 221 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 225 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 229 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 233 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 237 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 241 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 245 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 249 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 253 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 257 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 261 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 265 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 269 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 273 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 277 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 281 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 285 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 289 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 293 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 297 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 301 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 305 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 309 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 313 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 317 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 321 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 325 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 329 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 333 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 337 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 341 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 345 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 349 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 353 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 357 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 361 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 365 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 369 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 373 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 377 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 381 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 385 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 389 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 393 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 397 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 401 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 405 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 409 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 413 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 417 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 421 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 425 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 429 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 433 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 437 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 441 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 445 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 449 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 453 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 457 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 461 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 465 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 469 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 473 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 477 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 481 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 485 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 489 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 493 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt &
./dpm_simulator -t 497 0 -psm example/psm.txt -wl example/Generated_workload_1.5.txt
