function [fitresult, gof] = createFit(x1, x2, y)
%CREATEFIT(X1,X2,Y)
%  Create a fit.
%  
%  Data for 'untitled fit 1' fit:
%      X Input : x1
%      Y Input : x2
%      Z Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.
 
%  Auto-generated by MATLAB on 04-Jan-2021 22:33:23
 

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x1, x2, y );

% Set up fittype and options.
ft = fittype( 'a + b*x   + c*x^2   + d*y^2', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.474662969993381 0.187584947206236 0.464466964322128 0.932089536286421];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'y vs. x1, x2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x1', 'Interpreter', 'none' );
ylabel( 'x2', 'Interpreter', 'none' );
zlabel( 'y', 'Interpreter', 'none' );
grid on
view( -23.7, 6.3 );


